=== garyvidal/xquerrail2/src/_framework/schemas/routing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://xquerrail.com/routing"
    xmlns:routing = "http://xquerrail.com/routing"
    elementFormDefault="qualified"
    targetNamespace="http://xquerrail.com/routing"> 
<xs:element name="routes">
    <xs:complexType>
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="route" type="routeType"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:complexType name="routeType">
    <xs:sequence minOccurs="1">
        <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element name="default" type="defaultType" minOccurs="0" maxOccurs="1"/>     
            <xs:element name="prepend" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="append" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="to" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="routeAttributes"/>
</xs:complexType>
    
<xs:complexType name="defaultType">
  <xs:simpleContent>
    <xs:extension base="xs:string">
        <xs:attributeGroup ref="defaultAttributes"/>      
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>
    
<xs:complexType name="paramType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attributeGroup ref="defaultAttributes"/>   
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>
    
<xs:complexType name="replaceType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
           <xs:attribute name="path" type="xs:string"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>
    
<xs:attributeGroup name="defaultAttributes">
    <xs:attribute name="key" type="xs:string" use="required"></xs:attribute>
</xs:attributeGroup>    
<xs:attributeGroup name="routeAttributes">
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="pattern" type="xs:string"/>
    <xs:attribute name="method">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="post"/>
                <xs:enumeration value="put"/>
                <xs:enumeration value="get"/>
                <xs:enumeration value="delete"/>
                <xs:enumeration value="head"/>
                <xs:enumeration value="option"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="is-resource" type="xs:boolean">
    </xs:attribute>   
</xs:attributeGroup>
  
</xs:schema>

=== garyvidal/xquerrail2/src/_config/routes.xml
<routes xmlns="http://xquerrail.com/routing"  
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://xquerrail.com/routing file:../_framework/schemas/routing.xsd">
   <!--Define Resources Before Controllers-->
   <route id="_resources" pattern="^/resources/*" is-resource="true">
      <prepend></prepend>
   </route>
   
   <route id="application_resources" pattern="/(\i\c*)/resources/*" is-resource="true">
      
   </route>
   
   <route id="initialize" pattern="^/initialize(.xqy)?$" is-resource="true">
      <to>/_framework/initialize.xqy</to>
   </route>
   
   <route id="demo_index" pattern="^/$">
      <default key="_controller">demo:default:index:html</default>      
   </route>
   
   <route id="demo_login" pattern="^/login(.html)?">
      <default key="_controller">demo:default:login:html</default>
   </route>
   <route id="demo_logout" pattern="^/logout(.html)?">
      <default key="_controller">demo:default:logout:html</default>
   </route>   
   <route id="demo_default_index" pattern="^/(\i\c*[^/])/?$">
      <default key="_controller">demo:$1:index:html</default>      
   </route>
   
   <route id="docs_item" pattern="/docs/_/(.*)$">
      <default key="_controller">demo:docs:details:html</default>
      <param key="link">$1</param>
   </route>
   
   <route id="api_item" pattern="/api/_/(.*)$">
      <default key="_controller">demo:api:details:html</default>
      <param key="link">$1</param>
   </route>
   <route id="demo_default_controller_action_format" pattern="^/(\i\c*[^/])/(\i\c*)\.(html|xml|json)$">
      <default key="_controller">demo:$1:$2:$3</default>      
   </route>  
   
   <route id="demo_default_controller_action" pattern="^/(\i\c*[^/])/(\i\c*)$">
      <default key="_controller">demo:$1:$2:html</default>      
   </route>  
   
   
   <!--Default Routes-->
   <route id="default_index" pattern="^/(\i\c*[^/])/?$">
      <default key="_controller">application:$1:index:html</default>      
   </route>
   
   <route id="default_controller_action_format" pattern="^/(\i\c*[^/])/(\i\c*)\.(html|xml|json)$">
      <default key="_controller">application:$1:$2:$3</default>      
   </route>  
   
   <route id="default_controller_action" pattern="^/(\i\c*[^/])/(\i\c*)$">
      <default key="_controller">application:$1:$2:xml</default>      
   </route>  
   
</routes>
